document:
  name: Linee guida operative per la fruizione dei servizi SPID da parte dei minori

  description:
      Linee guida operative per la fruizione dei servizi SPID da parte dei minori
  tags:
    - spid
    - linee guida